"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# -----------------------------
# Core settings (Render-ready)
# -----------------------------
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-me")
DEBUG = os.environ.get("DEBUG", "0") == "1"

# Accept comma-separated list: "127.0.0.1,localhost,myapp.onrender.com"
_allowed_hosts_raw = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(",") if h.strip()]

# CSRF trusted origins (optional but recommended for Render/custom domains)
# Example: "https://myapp.onrender.com,https://draft.meudominio.com"
_csrf_trusted_raw = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_raw.split(",") if o.strip()]


# -----------------------------
# Application definition
# -----------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "league.apps.LeagueConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # se você tiver templates fora dos apps, coloque aqui
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "backend.wsgi.application"


# -----------------------------
# Database
# -----------------------------
# Render Postgres provides DATABASE_URL. Local dev can fall back to sqlite.
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    # Render: normalmente usa SSL. Local pode não usar.
    ssl_require = os.environ.get("DB_SSL_REQUIRE", "1") == "1"

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=ssl_require,
        )
    }

else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# -----------------------------
# Internationalization
# -----------------------------
LANGUAGE_CODE = "en-us"

# Recomendo São Paulo por estar alinhado com seu uso (-03:00).
# Se você preferir manter UTC, troque para "UTC".
TIME_ZONE = os.environ.get("TIME_ZONE", "America/Sao_Paulo")

USE_I18N = True
USE_TZ = True


# -----------------------------
# Static files (CSS, JavaScript, Images)
# -----------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise storage (ótimo pra Render sem S3/CDN)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Auth redirects (seus valores)
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/draft/1/board/"
LOGOUT_REDIRECT_URL = "/accounts/login/"


# -----------------------------
# Security (safe defaults for Render)
# -----------------------------
# Render sits behind a proxy; this makes Django understand https correctly.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Keep it strict in production, relaxed in DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# ✅ Local dev override: runserver não suporta HTTPS
# Use: set DJANGO_LOCAL=1 (cmd)  |  $env:DJANGO_LOCAL="1" (PowerShell)
# ==============================
# 🔧 LOCAL DEVELOPMENT OVERRIDE
# ==============================
if os.environ.get("DJANGO_LOCAL") == "1":
    DEBUG = True

    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False

