# Generated by Django 6.0.1 on 2026-01-21 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('snake', 'Snake'), ('linear', 'Linear')], default='snake', max_length=10)),
                ('rounds', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('pick_number', models.IntegerField(help_text='Pick dentro da rodada (1..N)')),
                ('overall_number', models.IntegerField(help_text='Pick geral (1..rounds*N)')),
                ('made_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='league.draft')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='league.team')),
            ],
            options={
                'ordering': ['overall_number'],
                'unique_together': {('draft', 'overall_number'), ('draft', 'round_number', 'pick_number')},
            },
        ),
    ]
