# Generated by Django 6.0.1 on 2026-01-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_draft_draftpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='overall_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='pick_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'player'), name='unique_player_per_draft'),
        ),
    ]
