# Generated by Django 6.0.1 on 2026-01-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GOL', 'Goleiro'), ('LAT', 'Lateral'), ('ZAG', 'Zagueiro'), ('MEI', 'Meia'), ('ATA', 'Atacante'), ('TEC', 'Técnico')], max_length=3),
        ),
    ]
