# Generated by Django 6.0.1 on 2026-01-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cartola_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
