# Generated by Django 6.0.1 on 2026-01-21 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_player_cartola_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_via', models.CharField(choices=[('DRAFT', 'Draft'), ('FA', 'Free Agency'), ('TRADE', 'Trade')], default='DRAFT', max_length=10)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='league.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_spots', to='league.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('draft', 'player'), name='uniq_player_per_draft_roster')],
            },
        ),
    ]
