# Generated by Django 6.0.1 on 2026-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_rosterspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterspot',
            name='dropped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rosterspot',
            name='acquired_via',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAIVER', 'Waiver'), ('FA', 'Free Agency'), ('TRADE', 'Trade')], default='DRAFT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='rosterspot',
            constraint=models.UniqueConstraint(condition=models.Q(('dropped_at__isnull', True)), fields=('player',), name='uniq_active_player_global'),
        ),
    ]
