# Generated by Django 6.0.1 on 2026-01-28 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_rosterspot_dropped_at_alter_rosterspot_acquired_via_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DRAFT', 'Draft'), ('ADD', 'Add (FA)'), ('DROP', 'Drop'), ('TRADE', 'Trade')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
    ]
