# Generated by Django 6.0.1 on 2026-01-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='league.draft')),
            ],
            options={
                'ordering': ['draft_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='LineupSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('GOL', 'Goleiro'), ('LAT', 'Lateral'), ('ZAG', 'Zagueiro'), ('MEI', 'Meia'), ('ATA', 'Atacante'), ('TEC', 'Técnico'), ('BENCH', 'Banco')], max_length=10)),
                ('set_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_spots', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_spots', to='league.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_spots', to='league.week')),
            ],
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('draft', 'number'), name='uniq_week_per_draft'),
        ),
        migrations.AddConstraint(
            model_name='lineupspot',
            constraint=models.UniqueConstraint(fields=('week', 'player'), name='uniq_player_per_week'),
        ),
        migrations.AddConstraint(
            model_name='lineupspot',
            constraint=models.UniqueConstraint(fields=('week', 'team', 'player'), name='uniq_player_team_week'),
        ),
    ]
