# Generated by Django 6.0.1 on 2026-01-28 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_week_lineupspot_week_uniq_week_per_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWeekScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('scouts', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='CARTOLA', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_scores', to='league.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='league.week')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week', 'player'), name='uniq_player_score_per_week')],
            },
        ),
    ]
