# Generated by Django 6.0.1 on 2026-01-28 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_playerweekscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='league',
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='matchup',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchups', to='league.team'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchups', to='league.team'),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='league.week'),
        ),
        migrations.AddConstraint(
            model_name='matchup',
            constraint=models.UniqueConstraint(fields=('week', 'home_team', 'away_team'), name='uniq_matchup_per_week'),
        ),
    ]
