# Generated by Django 6.0.1 on 2026-01-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_remove_matchup_league_matchup_away_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='is_playoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='is_postponed',
            field=models.BooleanField(default=False),
        ),
    ]
