# Generated by Django 6.0.1 on 2026-01-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_week_is_final_week_is_locked_week_is_playoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('formation', models.CharField(choices=[('343', '3-4-3'), ('352', '3-5-2'), ('451', '4-5-1'), ('442', '4-4-2'), ('433', '4-3-3'), ('532', '5-3-2'), ('541', '5-4-1')], default='433', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('MEI', 'Meia'), ('ATA', 'Atacante'), ('TEC', 'Técnico')], max_length=3)),
                ('slot_index', models.PositiveIntegerField()),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='league.lineup')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='league.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lineup',
            constraint=models.UniqueConstraint(fields=('fantasy_team', 'round_number'), name='uniq_lineup_team_round'),
        ),
        migrations.AddConstraint(
            model_name='lineupslot',
            constraint=models.UniqueConstraint(fields=('lineup', 'slot_type', 'slot_index'), name='uniq_lineup_slot'),
        ),
    ]
