# Generated by Django 6.0.1 on 2026-02-03 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_lineup_lineupslot_lineup_uniq_lineup_team_round_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lineup',
            name='uniq_lineup_team_round',
        ),
        migrations.RemoveConstraint(
            model_name='lineupslot',
            name='uniq_lineup_slot',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='player',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.RemoveConstraint(
            model_name='draftpick',
            name='unique_player_per_draft',
        ),
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='playerweekscore',
            name='source',
            field=models.CharField(choices=[('CARTOLA', 'Cartola'), ('MANUAL', 'Manual')], default='CARTOLA', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league.league'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='league.draft'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='league.player'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='league.team'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'overall_number'), name='uniq_overall_per_draft'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'round_number', 'pick_number'), name='uniq_round_pick_per_draft'),
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('draft', 'player'), name='uniq_player_per_draft_pick'),
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='fantasy_team',
        ),
        migrations.RemoveField(
            model_name='lineupslot',
            name='lineup',
        ),
        migrations.RemoveField(
            model_name='lineupslot',
            name='player',
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Lineup',
        ),
        migrations.DeleteModel(
            name='LineupSlot',
        ),
    ]
