# Generated by Django 6.0.1 on 2026-02-03 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_remove_lineup_uniq_lineup_team_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('343', '3-4-3'), ('352', '3-5-2'), ('442', '4-4-2'), ('433', '4-3-3'), ('532', '5-3-2'), ('541', '5-4-1')], default='433', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='lineupspot',
            name='uniq_player_per_week',
        ),
        migrations.RemoveConstraint(
            model_name='lineupspot',
            name='uniq_player_team_week',
        ),
        migrations.AddField(
            model_name='lineupspot',
            name='slot_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineupspot',
            name='slot_type',
            field=models.CharField(blank=True, choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('MEI', 'Meia'), ('ATA', 'Atacante'), ('TEC', 'Técnico')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lineupspot',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineup_spots', to='league.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='league.team'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='league.week'),
        ),
        migrations.AddField(
            model_name='lineupspot',
            name='lineup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='league.lineup'),
        ),
        migrations.AddConstraint(
            model_name='lineupspot',
            constraint=models.UniqueConstraint(fields=('lineup', 'slot_type', 'slot_index'), name='uniq_lineup_slot'),
        ),
        migrations.AddConstraint(
            model_name='lineupspot',
            constraint=models.UniqueConstraint(fields=('lineup', 'player'), name='uniq_player_in_lineup'),
        ),
        migrations.RemoveField(
            model_name='lineupspot',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='lineupspot',
            name='team',
        ),
        migrations.RemoveField(
            model_name='lineupspot',
            name='week',
        ),
        migrations.AddConstraint(
            model_name='lineup',
            constraint=models.UniqueConstraint(fields=('week', 'team'), name='uniq_lineup_week_team'),
        ),
    ]
