# Generated by Django 6.0.1 on 2026-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_lineup_remove_lineupspot_uniq_player_per_week_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lineupspot',
            name='uniq_lineup_slot',
        ),
        migrations.RemoveConstraint(
            model_name='lineupspot',
            name='uniq_player_in_lineup',
        ),
        migrations.AddConstraint(
            model_name='lineupspot',
            constraint=models.UniqueConstraint(condition=models.Q(('lineup__isnull', False), ('slot_index__isnull', False), ('slot_type__isnull', False)), fields=('lineup', 'slot_type', 'slot_index'), name='uniq_lineup_slot_filled'),
        ),
        migrations.AddConstraint(
            model_name='lineupspot',
            constraint=models.UniqueConstraint(condition=models.Q(('lineup__isnull', False), ('player__isnull', False)), fields=('lineup', 'player'), name='uniq_player_in_lineup_filled'),
        ),
    ]
