# Generated by Django 6.0.1 on 2026-02-05 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_remove_lineupspot_uniq_lineup_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faab_balance', models.PositiveIntegerField(default=100)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faab_budget', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='WaiverClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('INVALID', 'Invalid')], default='PENDING', max_length=10)),
                ('invalid_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('add_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_add_claims', to='league.player')),
                ('drop_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiver_drop_claims', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_claims', to='league.team')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'add_player', '-bid', 'created_at'], name='league_waiv_status_de2a4c_idx')],
            },
        ),
    ]
