# Generated by Django 6.0.1 on 2026-02-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_teambudget_waiverclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambudget',
            name='waiver_priority',
            field=models.PositiveIntegerField(db_index=True, default=999),
        ),
        migrations.AlterField(
            model_name='waiverclaim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('INVALID', 'Invalid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='waiverclaim',
            index=models.Index(fields=['team', 'status', 'created_at'], name='league_waiv_team_id_b0eb62_idx'),
        ),
        migrations.AddConstraint(
            model_name='waiverclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('team', 'add_player'), name='uniq_pending_claim_per_team_player'),
        ),
    ]
