# Generated by Django 6.0.1 on 2026-02-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_fix_waiver_priority_column'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='waiverclaim',
            name='uniq_pending_claim_per_team_player',
        ),
    ]
