# Generated by Django 6.0.1 on 2026-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_remove_waiverclaim_uniq_pending_claim_per_team_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='formation',
            field=models.CharField(choices=[('343', '3-4-3'), ('352', '3-5-2'), ('442', '4-4-2'), ('433', '4-3-3'), ('451', '4-5-1'), ('532', '5-3-2'), ('541', '5-4-1')], default='433', max_length=3),
        ),
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('rejected', 'Recusada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.draft')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sent', to='league.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='league.tradeproposal')),
            ],
        ),
    ]
