# Generated by Django 6.0.1 on 2026-04-17 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_alter_lineup_formation_tradeproposal_tradeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeproposal',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_proposals', to='league.draft'),
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('rejected', 'Recusada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trade_received', 'Trade recebida'), ('trade_accepted', 'Trade aceita'), ('trade_rejected', 'Trade rejeitada'), ('waiver_won', 'Waiver ganho'), ('waiver_lost', 'Waiver perdido')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='league.draft')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='league.team')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='league.tradeproposal')),
                ('waiver_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='league.waiverclaim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
