# Generated by Django 6.0.1 on 2026-04-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_tradeproposal_responded_at_alter_tradeproposal_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweekscore',
            name='is_home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerweekscore',
            name='match_display',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='playerweekscore',
            name='opponent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
