# Generated by Django 6.0.1 on 2026-04-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_playerweekscore_is_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cartola_club_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
