# Generated by Django 6.0.1 on 2026-04-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_player_cartola_club_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rosterspot',
            options={'ordering': ['manual_order', 'id']},
        ),
        migrations.AddField(
            model_name='rosterspot',
            name='manual_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
