# Generated by Django 6.0.1 on 2026-04-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_alter_rosterspot_options_rosterspot_manual_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweekscore',
            name='live_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('live', 'Ao vivo'), ('finished', 'Encerrado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='playerweekscore',
            name='unchanged_updates',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
