# Generated by Django 6.0.1 on 2026-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_playerweekscore_live_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerweekscore',
            old_name='unchanged_updates',
            new_name='unchanged_polls_count',
        ),
        migrations.AddField(
            model_name='playerweekscore',
            name='last_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
