# Generated by Django 6.0.1 on 2026-05-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_rename_unchanged_updates_playerweekscore_unchanged_polls_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerweekscore',
            name='match_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
